apiVersion: v1
kind: Namespace
metadata:
  name: vmz-wiki
  labels:
    name: vmz-wiki
    environment: production
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vmz-wiki-role
  namespace: vmz-wiki
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vmz-wiki-rolebinding
  namespace: vmz-wiki
subjects:
- kind: ServiceAccount
  name: vmz-wiki-sa
  namespace: vmz-wiki
roleRef:
  kind: Role
  name: vmz-wiki-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vmz-wiki-sa
  namespace: vmz-wiki 