apiVersion: v1
kind: Service
metadata:
  name: vmz-wiki-mongodb
  namespace: vmz-wiki
spec:
  selector:
    app: vmz-wiki-mongodb
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: vmz-wiki-redis
  namespace: vmz-wiki
spec:
  selector:
    app: vmz-wiki-redis
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: vmz-wiki-mongo-express
  namespace: vmz-wiki
spec:
  selector:
    app: vmz-wiki-mongo-express
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: vmz-wiki-redis-commander
  namespace: vmz-wiki
spec:
  selector:
    app: vmz-wiki-redis-commander
  ports:
  - port: 8082
    targetPort: 8081
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vmz-wiki-ingress
  namespace: vmz-wiki
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: vmz-wiki.example.com
    http:
      paths:
      - path: /mongo-express
        pathType: Prefix
        backend:
          service:
            name: vmz-wiki-mongo-express
            port:
              number: 8081
      - path: /redis-commander
        pathType: Prefix
        backend:
          service:
            name: vmz-wiki-redis-commander
            port:
              number: 8082 